=== AlignmentSystems/fix-orchestra/session2016/src/main/resources/xsd/FixSessions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Don Mendelson (FIX Protocol Ltd. (FPL)) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fixs="http://fixprotocol.io/2016/fixsessions" xmlns:dcterms="http://purl.org/dc/terms/" targetNamespace="http://fixprotocol.io/2016/fixsessions" elementFormDefault="qualified" version="1.0-rc2">
	<xs:annotation>
		<xs:documentation>
			FIX Session configuration
			Â© Copyright 2016-2017 FIX Protocol Limited
			Creative Commons Attribution-NoDerivatives 4.0
			International Public License
		</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dcterms.xsd"/>
	<xs:complexType name="annotation">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="documentation" type="fixs:documentation"/>
			<xs:element name="appinfo" type="fixs:appinfo"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="appinfo" mixed="true">
		<xs:annotation>
			<xs:documentation>Usage specific annotation, optionally with link to
				an external reference or standard
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="specUrl" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>Reference documentation</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="langId" type="xs:language"/>
	</xs:complexType>
	<xs:complexType name="documentation" mixed="true">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="langId" type="xs:language"/>
	</xs:complexType>
	<xs:complexType name="identifierType">
		<xs:sequence>
			<xs:element name="value" type="xs:anyType"/>
			<xs:element name="annotation" type="fixs:annotation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="layer_t">
		<xs:restriction base="xs:string">
			<xs:enumeration value="application"/>
			<xs:enumeration value="presentation"/>
			<xs:enumeration value="session"/>
			<xs:enumeration value="transport"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="protocolType">
		<xs:sequence>
			<xs:element name="annotation" type="fixs:annotation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>
				An application or session protocol name should match a 'protocol' name in 
				FIXRepository2016 schema.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="layer" type="fixs:layer_t"/>
		<xs:anyAttribute processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="serviceType">
		<xs:sequence>
			<xs:element name="annotation" type="fixs:annotation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Name of a service offering</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="file" type="xs:anyURI" use="required">
			<xs:annotation>
				<xs:documentation>URI of a FIX Orchestra file</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:anyAttribute processContents="lax"/>
	</xs:complexType>
	<xs:element name="sessions">
		<xs:annotation>
			<xs:documentation>
			This represents the current state of session configurations.
			Changes to configuration can represented with patch operations. See IETF RFC 5261
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metadata" type="dcterms:elementOrRefinementContainer"/>
				<xs:element name="session" type="fixs:sessionType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="sessionKey">
			<xs:selector xpath="fixs:session"/>
			<xs:field xpath="@name"/>
		</xs:key>
	</xs:element>
	<xs:complexType name="sessionType">
		<xs:sequence>
			<xs:element name="identifier" type="fixs:identifierType" maxOccurs="unbounded"/>
			<xs:element name="protocol" type="fixs:protocolType" maxOccurs="unbounded"/>
			<xs:element name="service" type="fixs:serviceType" maxOccurs="unbounded"/>
			<xs:element name="transport" type="fixs:transportType" maxOccurs="unbounded"/>
			<xs:element name="startTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="endTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="annotation" type="fixs:annotation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:anyAttribute processContents="lax"/>
	</xs:complexType>
	<xs:complexType name="transportType">
		<xs:sequence>
			<xs:element name="annotation" type="fixs:annotation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="address" type="xs:string" use="required"/>
		<xs:attribute name="use" type="fixs:transportUse_t"/>
		<xs:anyAttribute processContents="lax"/>
	</xs:complexType>
	<xs:simpleType name="transportUse_enum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="primary"/>
			<xs:enumeration value="secondary"/>
			<xs:enumeration value="alternate"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="transportUse_t">
		<xs:annotation>
			<xs:documentation>Extensible transport use</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="fixs:transportUse_enum xs:string"/>
	</xs:simpleType>
</xs:schema>

=== AlignmentSystems/fix-orchestra/session2016/src/test/resources/SampleSessions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2017 rel. 3 (x64) (http://www.altova.com)-->
<fixs:sessions xmlns:dcterms="http://purl.org/dc/terms/" xmlns:fixs="http://fixprotocol.io/2016/fixsessions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fixprotocol.io/2016/fixsessions FixSessions.xsd">
	<fixs:metadata>
		<dcterms:subject>Sample Sessions file</dcterms:subject>
		<dcterms:date>2017-04-05</dcterms:date>
	</fixs:metadata>
	<fixs:session name="XYZ-ABC" someOtherAttribute="thisIsExtensible">
		<!-- there can be any number of identifiers -->
		<fixs:identifier name="SenderCompID">
			<fixs:value>XYZ</fixs:value>
		</fixs:identifier>
		<fixs:identifier name="TargetCompID">
			<fixs:value>ABC</fixs:value>
		</fixs:identifier>
		<fixs:protocol name="FIX.5.0SP2" layer="application"/>
		<fixs:protocol name="FIXT.1.1" layer="session"/>
		<fixs:transport address="10.96.1.2:567"/>
		<fixs:startTime>2017-05-17T09:30:00Z</fixs:startTime>
	</fixs:session>
</fixs:sessions>
